import pandas as pd
from pandasql import sqldf
from langchain.tools import tool
from io import StringIO

@tool
def csv_qa_tool(question: str, csv_schema: str, csv_data:str) -> str:
    """
    Answer questions about a CSV file by converting them into SQL queries.
    arg: question, CSV schema, CSV data
    return: query
    """

    # Load CSV from string
    df = pd.read_csv(StringIO(csv_data))

    # Prompt for SQL generation
    sql_prompt = f"""
    You are an expert SQL developer.

    Table name: data
    Table schema:
    {csv_schema}

    Question:
    {question}

    Instruction:
    - Generate ONLY a valid SQLite SQL query
    - Do NOT add explanation
    - Do NOT use markdown
    - If query cannot be generated, output exactly: Error
    """
    # Assume sql_query is generated by LLM
    # (Agent will do this step)
    sql_query = "SELECT * FROM data LIMIT 5"

    try:
        result = sqldf(sql_query, {"data": df})
        explanation = f"The answer is shown based on the SQL query result. The table contains {len(result)} rows."

        return f"SQL Query:\n{sql_query}\n\nResult:\n{result}\n\nExplanation:\n{explanation}"

    except Exception as e:
        return f"Error while executing SQL query: {str(e)}"
